This notebook converts the raw data from the pickle files into the format required for the plots.

In [1]:
from __future__ import division
import glob 
import matplotlib.pyplot as plt
import pickle
import numpy as np 
import os
import time


from calc_num_IPIs import calc_num_IPIs_to_hear_echoes as nIPIs_to_mechoes
from calc_num_IPIs import calc_numtrials_per_echonumber 

In [2]:
results_folder = os.path.join('results','the_CPN_nIPIs_to_hear_all_echoes','the_CPN_nIPIS_to_hear_echoes_round_2')
results_files = glob.glob(results_folder+'/*.pkl')

In [20]:
results_folder

'results/the_CPN_nIPIs_to_hear_all_echoes/the_CPN_nIPIS_to_hear_echoes_round_2'

In [3]:
echoes_heard = {}
for each_resultfile in results_files:
    with open(each_resultfile, 'r') as one_file:
        data = pickle.load(one_file)
        echoes_heard[data['num_echoes']] = data['echo_ids']

    

In [4]:
get_90pctile = lambda X : np.percentile(X, 90, interpolation='nearest')

In [11]:
def echoes_once():
    all_echoes_once =  np.zeros((16,16))
    for i, each_echonum in enumerate(sorted(echoes_heard.keys())):
        start = time.time()
        print('each_echonum')
        Ntrials_allonce = [ nIPIs_to_mechoes(echoes_heard[each_echonum][j], each_echonum, each_echonum) for j in range(16)]
        ninety_pctile_once = map(get_90pctile, Ntrials_allonce)
        all_echoes_once[i,:] = ninety_pctile_once
        end_time = time.time()
        print('duration', end_time - start)
    return(all_echoes_once)

def echoes_twice():
    all_echoes_twice =  np.zeros((16,16))
    for i, each_echonum in enumerate(sorted(echoes_heard.keys())):
        start = time.time()
        print('each_echonum twice', each_echonum)
        Ntrials_alltwice = [ nIPIs_to_mechoes(echoes_heard[each_echonum][j], each_echonum, each_echonum,
                                            numtimes_allechoes=2) for j in range(16)]
        ninety_pctile_twice = map(get_90pctile, Ntrials_alltwice)
        all_echoes_twice[i,:] = ninety_pctile_twice
        end_time = time.time()
        print('duration', end_time - start)
    return(all_echoes_twice)

    
def echoes_median():
    median_once =  np.zeros((16,16))
    for i, each_echonum in enumerate(sorted(echoes_heard.keys())):
        start = time.time()
        print('each_echonum twice', each_echonum)
        Ntrials_median = []
        for j in range(16): 
            median_num = np.median(np.arange(1,each_echonum+1))
            Ntrials_median.append( nIPIs_to_mechoes(echoes_heard[each_echonum][j], median_num, each_echonum) )
        ninety_pctile_median = map(get_90pctile, Ntrials_median)
        median_once[i,:] = ninety_pctile_median
        end_time = time.time()
        print('duration', end_time - start)
    return(median_once)

In [12]:
funcs_list = [echoes_once, echoes_twice, echoes_median]
run_funcs = lambda X : X()

In [13]:
formatted_results = map(run_funcs, funcs_list)

each_echonum
('duration', 14.064870119094849)
each_echonum
('duration', 25.76563787460327)
each_echonum
('duration', 26.70962691307068)
each_echonum
('duration', 31.37025809288025)
each_echonum
('duration', 36.26642298698425)
each_echonum
('duration', 39.98077201843262)
each_echonum
('duration', 43.6704580783844)
each_echonum
('duration', 48.034284830093384)
each_echonum
('duration', 49.23436689376831)
each_echonum
('duration', 53.02928018569946)
each_echonum
('duration', 57.75196385383606)
each_echonum
('duration', 62.716432094573975)
each_echonum
('duration', 67.8208360671997)
each_echonum
('duration', 72.2525839805603)
each_echonum
('duration', 78.5224928855896)
each_echonum
('duration', 83.90560412406921)
('each_echonum twice', 1)
('duration', 6.905030965805054)
('each_echonum twice', 3)
('duration', 13.068014860153198)
('each_echonum twice', 5)
('duration', 14.231063842773438)
('each_echonum twice', 7)
('duration', 17.203804969787598)
('each_echonum twice', 9)
('duration', 20.1900

In [19]:
plotdata = {'all_once' : formatted_results[0],
            'all_twice' : formatted_results[1],
             'median_once' : formatted_results[2]
           }

In [22]:
with open('plots/round2_plotdata.pkl', 'wb') as handle:
    pickle.dump(plotdata, handle)

In [14]:
formatted_results[0]

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 2., 2., 2., 2., 2., 2., 2., 3., 3., 3., 3., 3., 3., 3.],
       [1., 2., 2., 2., 2., 2., 3., 3., 3., 3., 3., 3., 3., 4., 4., 4.],
       [1., 2., 2., 2., 2., 3., 3., 3., 3., 3., 3., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 3., 3., 3., 3., 3., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 3., 3., 3., 3., 3., 4., 4., 4., 4., 4., 4., 5.],
       [2., 2., 2., 3., 3., 3., 3., 3., 4., 4., 4., 4., 4., 4., 5., 5.],
       [2., 2., 2., 3., 3., 3., 3., 4., 4., 4., 4., 4., 5., 5., 5., 5.],
       [2., 2., 2., 3., 3., 3., 3., 4., 4., 4., 4., 4., 5., 5., 5., 5.],
       [2., 2., 2., 3., 3., 3., 3., 4., 4., 4., 4., 4., 5., 5., 5., 5.],
       [2., 2., 3., 3., 3., 3., 4., 4., 4., 4., 4., 5., 5., 5., 5., 5.],
       [2., 2., 3., 3., 3., 3., 4., 4., 4., 4., 4., 5., 5., 5., 5., 5.],
       [2., 2., 3., 3., 3., 3., 4., 4., 4., 4., 4., 5., 5., 5., 5., 5.],
       [2., 2., 3., 3., 3., 3., 4., 4., 4., 4., 4.,

In [15]:
formatted_results[1]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 3., 3., 3., 3., 4., 4., 4., 4., 4., 5., 5., 5., 5., 5., 5.],
       [3., 3., 3., 4., 4., 4., 4., 5., 5., 5., 5., 5., 6., 6., 6., 6.],
       [3., 3., 3., 4., 4., 4., 5., 5., 5., 5., 6., 6., 6., 6., 6., 7.],
       [3., 3., 4., 4., 4., 4., 5., 5., 5., 6., 6., 6., 6., 6., 7., 7.],
       [3., 3., 4., 4., 4., 5., 5., 5., 5., 6., 6., 6., 6., 7., 7., 7.],
       [3., 3., 4., 4., 4., 5., 5., 5., 5., 6., 6., 6., 7., 7., 7., 7.],
       [3., 3., 4., 4., 4., 5., 5., 5., 6., 6., 6., 6., 7., 7., 7., 7.],
       [3., 3., 4., 4., 5., 5., 5., 5., 6., 6., 6., 6., 7., 7., 7., 8.],
       [3., 4., 4., 4., 5., 5., 5., 5., 6., 6., 6., 7., 7., 7., 7., 8.],
       [3., 4., 4., 4., 5., 5., 5., 6., 6., 6., 6., 7., 7., 7., 8., 8.],
       [3., 4., 4., 4., 5., 5., 5., 6., 6., 6., 7., 7., 7., 7., 8., 8.],
       [3., 4., 4., 4., 5., 5., 5., 6., 6., 6., 7., 7., 7., 7., 8., 8.],
       [3., 4., 4., 4., 5., 5., 5., 6., 6., 6., 7.,

In [16]:
formatted_results[2]

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2., 2.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,